---
title: "Proposal Simulation 9.26"
author: "Renjie Luo"
date: "2024-09-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

```{r}
library(doParallel)
library(foreach)
library(carat)
library(survival)
library(openxlsx)
```

```{r functions}
permuted_block = function(n, block_size = 4) {
    assignments = numeric(n)
    ts = c(1, 0)

    num_full_blocks = n %/% block_size
    remaining_patients = n %% block_size

  if (remaining_patients %% 2 != 0) {
    stop("Patient number must be even.")
  }

  for (i in 1:num_full_blocks) {
    block = rep(ts, each = block_size / length(ts))
    assignments[((i - 1) * block_size + 1):(i * block_size)] = sample(block)
  }

  if (remaining_patients == 2) {
    last_block = sample(c("A", "B"))
    assignments[(n - 1):n] = last_block
  }

  return(assignments)
}


Exp_generate_data = function(n, m0 = 40, k=2, beta) {
  t = c(permuted_block(2 * m0), rep(NA, n - 2 * m0))
  X = sample(c(1, -1), n, replace = T)
  Z = replicate(k, sample(c(1, -1), n, replace = T))
  # HR = exp(cbind(t,(1-t),X,X*t,Z)%*%beta)[1:(2*m0)]
  exp_mean = exp(cbind(t,(1-t),X,X*t,Z)%*%beta)[1:(2*m0)]
  S = rexp(2*m0,rate=1/exp_mean)
  C=runif(n,0,2)
  E=runif(2 * m0,0,1)
  E=c(ifelse(S[1:(2*m0)]<=C[1:(2*m0)],1,0),rep(NA, n - 2 * m0))
  A = c(rep(9999,2*m0),rep(0, n - 2 * m0))
  Cohort=c(rep(0,2*m0),rep(NA, n - 2 * m0))
  
  patients=cbind(X, Z, t,S,C,E,A,Cohort)
  colnames(patients)[1]="X"
  colnames(patients)[2:(1+k)]=paste0("Z",1:k)
  colnames(patients)[(2+k):ncol(patients)]=c("t","S","C","E","A","Cohort")
  return(patients)
}


#Cox_generate_data(n=400,m0=40,k=2,beta=c(0.5,0.5,1, -1, 0.5, 0.5))

list_summary_exp=function(list){
  N11=function(dat){sum(dat[,"X"]==1&dat[,"t"]==1)}
  Nm11=function(dat){sum(dat[,"X"]==-1&dat[,"t"]==1)}
  N10=function(dat){sum(dat[,"X"]==1&dat[,"t"]==0)}
  Nm10=function(dat){sum(dat[,"X"]==-1&dat[,"t"]==0)}
  P1=function(dat){sum(dat[,"X"]==1&dat[,"t"]==0)/sum(dat[,"X"]==1)}
  Pm1=function(dat){sum(dat[,"X"]==-1&dat[,"t"]==1)/sum(dat[,"X"]==-1)}
  E=function(dat){sum(dat[,"E"]==1)}
  Z111=function(dat){sum(dat[,"Z1"]==1&dat[,"t"]==1)}
  Z1m11=function(dat){sum(dat[,"Z1"]==-1&dat[,"t"]==1)}
  Z110=function(dat){sum(dat[,"Z1"]==1&dat[,"t"]==0)}
  Z1m10=function(dat){sum(dat[,"Z1"]==-1&dat[,"t"]==0)}
  Z211=function(dat){sum(dat[,"Z2"]==1&dat[,"t"]==1)}
  Z2m11=function(dat){sum(dat[,"Z2"]==-1&dat[,"t"]==1)}
  Z210=function(dat){sum(dat[,"Z2"]==1&dat[,"t"]==0)}
  Z2m10=function(dat){sum(dat[,"Z2"]==-1&dat[,"t"]==0)}
  
  N11_res=lapply(list,N11)
  Nm11_res=lapply(list,Nm11)
  N10_res=lapply(list,N10)
  Nm10_res=lapply(list,Nm10)
  
  P1_res=lapply(list,P1)
  Pm1_res=lapply(list,Pm1)
  E_res=lapply(list,E)
  
  Z111_res=lapply(list,Z111)
  Z1m11_res=lapply(list,Z1m11)
  Z110_res=lapply(list,Z110)
  Z1m10_res=lapply(list,Z1m10)
  Z211_res=lapply(list,Z211)
  Z2m11_res=lapply(list,Z2m11)
  Z210_res=lapply(list,Z210)
  Z2m10_res=lapply(list,Z2m10)
  
  return(c(paste0(round(mean(do.call(c, N11_res)),3),"(",round(sd(do.call(c, N11_res)),3),")"),
           paste0(round(mean(do.call(c, Nm11_res)),3),"(",round(sd(do.call(c, Nm11_res)),3),")"),
           paste0(round(mean(do.call(c, N10_res)),3),"(",round(sd(do.call(c, N10_res)),3),")"),
           paste0(round(mean(do.call(c, Nm10_res)),3),"(",round(sd(do.call(c, Nm10_res)),3),")"),
           paste0(round(mean(do.call(c, P1_res)),3),"(",round(sd(do.call(c, P1_res)),3),")"),
         paste0(round(mean(do.call(c, Pm1_res)),3),"(",round(sd(do.call(c, Pm1_res)),3),")"),
         paste0(round(mean(do.call(c, E_res)),3),"(",round(sd(do.call(c, E_res)),3),")"),
         paste0(round(mean(do.call(c, Z111_res)),3),"(",round(sd(do.call(c, Z111_res)),3),")"),
         paste0(round(mean(do.call(c, Z1m11_res)),3),"(",round(sd(do.call(c, Z1m11_res)),3),")"),
         paste0(round(mean(do.call(c, Z110_res)),3),"(",round(sd(do.call(c, Z110_res)),3),")"),
         paste0(round(mean(do.call(c, Z1m10_res)),3),"(",round(sd(do.call(c, Z1m10_res)),3),")"),
         paste0(round(mean(do.call(c, Z211_res)),3),"(",round(sd(do.call(c, Z211_res)),3),")"),
         paste0(round(mean(do.call(c, Z2m11_res)),3),"(",round(sd(do.call(c, Z2m11_res)),3),")"),
         paste0(round(mean(do.call(c, Z210_res)),3),"(",round(sd(do.call(c, Z210_res)),3),")"),
         paste0(round(mean(do.call(c, Z2m10_res)),3),"(",round(sd(do.call(c, Z2m10_res)),3),")")
           ))
}
```


```{r}
#r=41
#data=Exp_generate_data(n=400,m0=20,k=2,beta=c(0.5,0.5,1, -1, 0.5, 0.5))
#m0=40
#c=1
#Consider Delayed response with arrival time interval e^{-1}
Exp_CR=function(data,m0=40,beta){
   data[,"t"]=sample(c(0,1),nrow(data),replace = T)
   for (c in 1:((nrow(data)-2*m0)/10)){
    data[(2*m0+(c*10)-9):(2*m0+(c*10)),"Cohort"]=rep(c,10)
    data[1:(2*m0+(c-1)*10),"A"]=data[1:(2*m0+(c-1)*10),"A"]+rexp(1,rate=1)
    data_before=data[1:(2*m0+(c-1)*10),]
    data_before_responsed=data.frame(data_before[pmin(data_before[,"A"],data_before[,"S"],data_before[,"C"])!=data_before[,"A"],])

    new_patient=data.frame(data[(2*m0+c*10-9):(2*m0+c*10),])
    
    new_expmean=exp(cbind(new_patient[,"t"],(1-new_patient[,"t"]),new_patient[,"X"],new_patient[,"X"]*new_patient[,"t"],new_patient[,"Z1"],new_patient[,"Z2"])%*%beta)

    data[(2*m0+c*10-9):(2*m0+c*10),"S"]=rexp(10,rate=1/new_expmean)
    data[(2*m0+c*10-9):(2*m0+c*10), "E"] =ifelse(data[(2*m0+c*10-9):(2*m0+c*10),"S"]<data[(2*m0+c*10-9):(2*m0+c*10),"C"],1,0)
  }
  
  return(data)
}


Exp_CAR=function(data,m0=40,beta){
  cov=data[,1:3]
  CARres=HuHuCAR(cov)
  data[,"t"]=ifelse(CARres$assignments=="A",1,0)
  
   for (c in 1:((nrow(data)-2*m0)/10)){
    data[(2*m0+(c*10)-9):(2*m0+(c*10)),"Cohort"]=rep(c,10)
    data[1:(2*m0+(c-1)*10),"A"]=data[1:(2*m0+(c-1)*10),"A"]+rexp(1,rate=1)
    data_before=data[1:(2*m0+(c-1)*10),]
    data_before_responsed=data.frame(data_before[pmin(data_before[,"A"],data_before[,"S"],data_before[,"C"])!=data_before[,"A"],])
    
    new_patient=data.frame(data[(2*m0+c*10-9):(2*m0+c*10),])
    
    new_expmean=exp(cbind(new_patient[,"t"],(1-new_patient[,"t"]),new_patient[,"X"],new_patient[,"X"]*new_patient[,"t"],new_patient[,"Z1"],new_patient[,"Z2"])%*%beta)

    data[(2*m0+c*10-9):(2*m0+c*10),"S"]=rexp(10,rate=1/new_expmean)
    data[(2*m0+c*10-9):(2*m0+c*10), "E"] =ifelse(data[(2*m0+c*10-9):(2*m0+c*10),"S"]<data[(2*m0+c*10-9):(2*m0+c*10),"C"],1,0)
  }
  
  return(data)
}


Exp_CARA=function(data,m0 = 40 ,beta){
  for (c in 1:((nrow(data)-2*m0)/10)){
    data[(2*m0+(c*10)-9):(2*m0+(c*10)),"Cohort"]=rep(c,10)
    data[1:(2*m0+(c-1)*10),"A"]=data[1:(2*m0+(c-1)*10),"A"]+rexp(1,rate=1)
    data_before=data.frame(data[1:(2*m0+(c-1)*10),])
    data_before_responsed=data.frame(data_before[pmin(data_before[,"A"],data_before[,"S"],data_before[,"C"])!=data_before[,"A"],])
    
    surv_fit_tho = survreg(Surv(pmin(A,S,C)) ~ t+X+t:X,data=data_before,dist="exponential")

    new_patient=data.frame(data[(2*m0+c*10-9):(2*m0+c*10),c("X","t")])
    new_patient[,"t"]=rep(1,10)
    new_patient1=new_patient
    
    new_patient[,"t"]=rep(0,10)
    new_patient0=new_patient
    
    new_expmean1=exp(predict(surv_fit_tho, newdata = new_patient1, type = "lp"))
    new_expmean0=exp(predict(surv_fit_tho, newdata = new_patient0, type = "lp"))
    
    rho=pexp(new_expmean1)/(pexp(new_expmean1)+pexp(new_expmean0))
    
    data[(2*m0+c*10-9):(2*m0+c*10),"t"]=ifelse(runif(10)<rho,1,0)
    
    new_patient=data.frame(data[(2*m0+c*10-9):(2*m0+c*10),])
    
    new_expmean=exp(cbind(new_patient[,"t"],(1-new_patient[,"t"]),new_patient[,"X"],new_patient[,"X"]*new_patient[,"t"],new_patient[,"Z1"],new_patient[,"Z2"])%*%beta)
    
    
    data[(2*m0+c*10-9):(2*m0+c*10),"S"]=rexp(n=10,rate=1/new_expmean)
    data[(2*m0+c*10-9):(2*m0+c*10), "E"] =ifelse(data[(2*m0+c*10-9):(2*m0+c*10),"S"]<data[(2*m0+c*10-9):(2*m0+c*10),"C"],1,0)
  }
  
  return(data)
}

#c=1
#m0=40
#data=Exp_generate_data(n=400,k = 2,beta=c(0.5,0.5,1, -1, 0.5, 0.5))
#r=2*m0+c*10-9
Exp_New=function(data,m0 = 40 ,k=2,beta,omega=rep(0.25,4),p=0.8){
   for (c in 1:((nrow(data)-2*m0)/10)){
    data[(2*m0+(c*10)-9):(2*m0+(c*10)),"Cohort"]=rep(c,10)
    data[1:(2*m0+(c-1)*10),"A"]=data[1:(2*m0+(c-1)*10),"A"]+rexp(1,rate=1)
    data_before=data.frame(data[1:(2*m0+(c-1)*10),])
    
    # data_before_responsed=data.frame(data_before[pmin(data_before[,"A"],data_before[,"S"],data_before[,"C"])!=data_before[,"A"],])
    
    for (r in (2*m0+c*10-9):(2*m0+c*10)){

    Xn = data[r, "X"]
    Z1 = data[r, "Z1"]
    Z2 = data[r, "Z2"]
    data_before_Xn=data_before[data_before[,"X"]==Xn,]
    # data_before_responsed_Xn=data.frame(data_before_responsed[data_before_responsed[,"X"]==Xn,])

    surv_fit_Xn=survreg(Surv(pmin(A,S,C)) ~ t,data=data_before_Xn,dist = "exponential")
    #summary(surv_fit_Xn)

    data_new1=rbind(data_before_Xn,data[r,])
    data_new1[nrow(data_new1),"t"]=1
    
    data_new0=rbind(data_before_Xn,data[r,])
    data_new0[nrow(data_new0),"t"]=0
    
    new_patient1=as.data.frame(data_new1[nrow(data_new1),c("t","X","Z1","Z2")])
    new_patient0=as.data.frame(data_new0[nrow(data_new0),c("t","X","Z1","Z2")])
    
    expmean1_Xn=exp(predict(surv_fit_Xn, newdata = new_patient1, type = "lp"))
    expmean0_Xn=exp(predict(surv_fit_Xn, newdata = new_patient0, type = "lp"))
    
    rho=pexp(expmean1_Xn)/(pexp(expmean1_Xn)+pexp(expmean0_Xn))
    

    Dn1 = sum(data_new1[, "t"] == 1 &
                data_new1[, "X"] == Xn) - rho * sum(data_new1[, "X"] == Xn)
    Dn2 = sum(data_new0[, "t"] ==1 &
                data_new0[, "X"] == Xn) - rho * sum(data_new0[, "X"] == Xn)
    
    Dn1k = numeric()
    Dn2k = numeric()

      Dn1k=append(
        Dn1k,
        sum(
          data_new1[, "t"] == 1 &
            data_new1[, "X"] == Xn &
            data_new1[, "Z1"] == Z1
        ) -
          rho * sum(data_new1[, "X"] == Xn &
                      data_new1[, "Z1"] == Z1)
      )
      
      Dn1k=append(
        Dn1k,
        sum(
          data_new1[, "t"] == 1 &
            data_new1[, "X"] == Xn &
            data_new1[, "Z2"] == Z2
        ) -
          rho * sum(data_new1[, "X"] == Xn &
                      data_new1[, "Z2"] == Z2)
      )

     Dn2k=append(
        Dn2k,
        sum(
          data_new0[, "t"] == 1 &
            data_new0[, "X"] == Xn &
            data_new0[, "Z1"] == Z1
        ) -
          rho * sum(data_new0[, "X"] == Xn &
                    data_new0[, "Z1"] == Z1)
      )
     
     Dn2k=append(
        Dn2k,
        sum(
          data_new0[, "t"] == 1 &
            data_new0[, "X"] == Xn &
            data_new0[, "Z2"] == Z2
        ) -
          rho * sum(data_new0[, "X"] == Xn &
                    data_new0[, "Z2"] == Z2)
      )


    Dn1k1k2 = sum(data_new1[, "t"] == 1 &
                    data_new1[, "X"] == Xn &
                    data_new1[, "Z1"] == Z1 &
                    data_new1[, "Z2"] == Z2) -
      rho * sum(data_new1[, "X"] == Xn &
                  data_new1[, "Z1"] == Z1&
                    data_new1[, "Z2"] == Z2)

       Dn2k1k2 = sum(data_new0[, "t"] == 1 &
                    data_new0[, "X"] == Xn &
                    data_new0[, "Z1"] == Z1 &
                    data_new0[, "Z2"] == Z2) -
      rho * sum(data_new0[, "X"] == Xn &
                  data_new0[, "Z1"] == Z1&
                    data_new0[, "Z2"] == Z2)
    
    #omega=rep(0.25,4)
    Imbn1 = omega[1] * Dn1 ^ 2 + sum(omega[2:(length(omega) - 1)] * Dn1k ^
                                       2) + omega[length(omega)] * Dn1k1k2 ^ 2
    Imbn2 = omega[1] * Dn2 ^ 2 + sum(omega[2:(length(omega) - 1)] * Dn2k ^
                                       2) + omega[length(omega)] * Dn2k1k2 ^ 2

    if (is.na(Imbn1 > Imbn2) |
        is.na(Imbn1 < Imbn2) |
        is.na(Imbn1 == Imbn2)) {
      data[r, "t"] = sample(c(1, 0), 1, prob = c(0.5, 0.5))
    }
    else if (Imbn1 > Imbn2) {
      data[r, "t"] = sample(c(1, 0), 1, prob = c(1 - p, p))

    }
    else if (Imbn1 == Imbn2) {
      data[r, "t"] = sample(c(1, 0), 1, prob = c(0.5, 0.5))
    }
    else if (Imbn1 < Imbn2) {
      data[r, "t"] = sample(c(1, 0), 1, prob = c(p, 1 - p))
    }
    }
    new_patient=data.frame(data[(2*m0+c*10-9):(2*m0+c*10),])
    new_expmean=exp(cbind(new_patient[,"t"],(1-new_patient[,"t"]),new_patient[,"X"],new_patient[,"X"]*new_patient[,"t"],new_patient[,"Z1"],new_patient[,"Z2"])%*%beta)
    data[(2*m0+c*10-9):(2*m0+c*10),"S"]=rexp(10,rate=1/new_expmean)
    data[(2*m0+c*10-9):(2*m0+c*10),"E"] =ifelse(data[(2*m0+c*10-9):(2*m0+c*10),"S"]<data[(2*m0+c*10-9):(2*m0+c*10),"C"],1,0)

    
  }
  
  return(data)
}
```


```{r}
#Assuming random censoring time
no_cores <- detectCores()
registerDoParallel(cores=no_cores)

init_beta=c(0.2,0.2,0.8, -0.8, 0.2, 0.2)

set.seed(2024)
Exp_CR_pts_list <- foreach(i = 1:1000, .export = ls(envir = globalenv()),.packages = "survival") %dopar% {
  Exp_CR(
    data = Exp_generate_data(
      400,
      k = 2,
      beta=init_beta
    ),
    beta=init_beta
  )
}


Exp_CAR_pts_list <- foreach(i = 1:1000, .export = ls(envir = globalenv()),.packages = c("survival","carat")) %dopar% {
  Exp_CAR(
    data = Exp_generate_data(
      400,
      k = 2,
      beta=init_beta
    ),
    beta=init_beta
  )
}

Exp_CARA_pts_list <- foreach(i = 1:1000, .export = ls(envir = globalenv()),.packages = "survival") %dopar% {
  Exp_CARA(
    data = Exp_generate_data(
      400,
      k = 2,
      beta=init_beta
    ),
    beta=init_beta
  )
}

Exp_NEW_pts_list <- foreach(i = 1:1000, .errorhandling = 'pass', .export = ls(envir = globalenv()),.packages = "survival") %dopar% {
  Exp_New(
    data = Exp_generate_data(
      n=400,
      k = 2,
      beta=init_beta
    ),
    beta=init_beta
  )
}

```

```{r}
Exp_res=data.frame(
list_summary_exp(Exp_CR_pts_list),
list_summary_exp(Exp_CAR_pts_list),
list_summary_exp(Exp_CARA_pts_list),
list_summary_exp(Exp_NEW_pts_list)
)

colnames(Exp_res)=c("CR","CAR","CARA","Proposed")
rownames(Exp_res)=c("N11","N-11","N10","N-10","P1","P-1","Events","Z1_11","Z1_-11","Z1_10","Z1_-10","Z2_11","Z2_-11","Z2_10","Z2_-10")

write.xlsx(Exp_res, file="/Users/renjieluo/Desktop/untitled folder/Exp_res.xlsx",rowNames=T, overwrite = TRUE)
#save.image(file = "/Users/renjieluo/Desktop/untitled folder/Exp and Cox_res.RData")
```

